spring:
  cloud:
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
            issuer-uri: "http://keycloak:8080/realms/master" # Add this line

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://eureka-server:8761/eureka/"
